packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@prisma/client': true
  '@swc/core': true
  prisma: true
  tsx: true
  esbuild: true
  sharp: false
  unrs-resolver: false
